---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: {{ list (.Values.opsManager.projectName | lower)  "root" | join "-" | quote }} 
spec:
  passwordSecretKeyRef:
    name: {{ .Values.rootSecret }}
    key: password
  username: "root" 
  db: "admin"
  mongodbResourceRef:
    name: {{ .Values.replicaSetName | lower | quote }}
  roles:
    - db: "admin"
      name: "root"