apiVersion: v1
data:
  baseUrl: {{ .Values.opsManager.baseUrl | trimSuffix "/" }}
  orgId: {{ .Values.opsManager.orgId }}
  projectName: {{ .Values.opsManager.projectName }}
  {{- if .Values.opsManager.tlsEnabled }}
  sslMMSCAConfigMap: {{ .Values.opsManager.caConfigmap }}
  sslRequireValidMMSServerCertificates: ‘true’
  {{- end }}
kind: ConfigMap
metadata:
  name: project-{{ .Values.opsManager.projectName | lower }}
  namespace: {{ .Release.Namespace }}