---

replicaSetName: blockstore0

mongoDBVersion: 5.0.8-ent
mongoDBFCV: "5.0"

replicas: 1

logLevel: DEBUG

auth:
  scram:
    enabled: true
  ldap:
    enabled: false

opsManager:
  tlsEnabled: true
  baseUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
  orgId: 626deb01f7d72e132e83d321
  projectName: blockStore
  omSecret: k8s-om
  caConfigmap: om-ca-cert

resources:
  limits:
    cpu: 2
    mem: 4Gi
  requests:
    cpu: 1
    mem: 4Gi

storage:
  persistenceType: single
  single:
    size: 5Gi
    storageClass: data
  multi:
    data:
      size: 5Gi
      storageClass: dataClass
    journal:
      size: 5Gi
      storageClass: journalClass
    logs:
      size: 5Gi
      storageClass: logClass

tls:
  enabled: true
  caConfigMap: custom-ca

extAccess:
  enabled: false

mongoDBAdminPasswdSecret: dev-adm-passwd

kmip:
  enabled: false
  host: kmip-svc.mongodb.svc.cluster.local
  port: 5696
